### ISSUE TITLE
NPE on accessing visualization for a specific gene  

### ISSUE THREAD

**Issue by ppavlidis** [ppavlidis/Gemma#14] opened 2017-05-29 21:42 UTC
This does not seem specific to a particular data set; happens with either

http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=2467
http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=10628

Visualization tab, enter "STAT1". Yields:

```
Error during read
java.lang.NullPointerException
Details:
ubic.gemma.core.search.GeneSetSearchImpl.goTermToGeneSet (379)
ubic.gemma.core.search.GeneSetSearchImpl.findByGoTermName (150)
sun.reflect.NativeMethodAccessorImpl.invoke (57)
```
Other genes I tried are OK.

Seems problem at that line is a missing null check, though for something that shouldn't be null -- a GO term label. The code fix is easy (`term.getLabel() != null && ...`) but I'm wondering what the underlying cause is.

**Comment by tesar-stepan** [comment] 2017-06-28 22:41
I can not reproduce this bug anymore.
The fix to prevent the error was rolled out with one of the recent hotfixes, but when I change the code back I am not getting an NPE anymore. The root cause might have been fixed within the big changes that were made in DAOs and services recently. I will add a warning to output when the label is null, in case this happens again in the future.

**Closed** 2017-06-30 00:24 UTC
Labels: bug
